[[libhgscvrp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06eae66478d6cf1ba70da7b6906f81b4efe3c979"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "fb4fd8f271624e95c5773a4cdfd5a057c801e6d5e416a716e26cc95c0c9bbf25"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libhgscvrp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d190c25c5ef7c0d5732be020dd723183d347497"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "dc3d25794e4b7b48a93f25980814378588fd71b8024a48e0d957f58a7563bdb3"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libhgscvrp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e28e6e2851ee61c9ec1f002dc1551badc6e13ed"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "97ac39fd642f6d235d35afbce6e2a2efbeac00c1d5d83c4708c37dcf9e56e797"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libhgscvrp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7de5db09c34c25ecd03ac7cc627a679dacdddb3"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "069443b1f448b5e48954bb51e35552b860bfdf310573f7fc949c69bc51cc7888"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libhgscvrp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6192fe46b36bfe6a34ee67d6934d2bcf7f537a3c"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "15cae87dc6b3941fa152b306747de63128ab1e21f99775bd2271ce4c7051eaba"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libhgscvrp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2415d2c13f47e6e470cee392c516b40157ff9485"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "d5e7056aee41819dfb0253f7c3f7ea5230160fa48ffffa78bcffb98d8ef00e74"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libhgscvrp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "026a2469da2fb0d7bdb3e27440dabe148893dbe1"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "3e84437571f596152e5951a595806f47c8ac0f08db6d0641dd1dfe46b07ab09e"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libhgscvrp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a60e7cf5a5ff09177d3e28bf610d5d0a1eb3922b"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "edee30ed2472e1a792251ed162ad4fa95b03fc2b95e82bfc9cb8d2008b21f8cf"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libhgscvrp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be7d37ec04f4ddcd795546b89dd00a42dd15429"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "53720aa5c48dbb816586b76a26355d0e77476397fc9a2be2521533c222164227"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libhgscvrp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddc6f95bcfb4d211736159aa4fdcbb3173bb6ad1"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "127687a6dd8c0b19ce8103f3a66bdc143b52b52cbac0ddcab13065342667811c"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libhgscvrp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6402bf3b01b91bebc097cfb1540b2294d9c4e7c"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "15542e17d36fe699054cca6f492af67463afc7306284633e316503a2bbd9b09b"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libhgscvrp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40d080063e8659128c96a666038cb0bb2545ba09"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "4967df628af3a4cfc73cb513e4337e7fb5a2f1cf5fdce361f9f5c318af471b5b"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libhgscvrp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "728e837b38b195c09047c5504fc2ce934bd44e4b"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "5b9a07bbca6237a16cb1afa99af32facd84db7ee9854bfef007989fa23b7b2d5"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libhgscvrp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8029935cc808e0a6f6ba3ddb2c31e85f6fbcce4"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "17610b1812ada40d4e72370e911b1dc725d9c99ba84af65f319739466cd8022e"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libhgscvrp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c68af4c0abd36659a3aea228fde1f42b6b1dfaea"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "26098479d3bf6c1d2471260a5cc22afa9b3472633933521b50895915992562fc"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-linux-musl-cxx03.tar.gz"
[[libhgscvrp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21b379b72d34d1d4fa1941fbd966829e6985e96d"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "e190eb5d0b5cff0442e85c73fcedc696947330a8aa4b28b0d54aeda4a4d569d0"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-linux-musl-cxx11.tar.gz"
[[libhgscvrp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2034be7b157093e830c1804165dafda7cb459e2"
os = "windows"

    [[libhgscvrp.download]]
    sha256 = "5405b026483d56e568af24d4b794751becb97dfda0bf729857a353308ccc476f"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libhgscvrp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "553d2c39c49722d88699091707220fd5ae83cc40"
os = "windows"

    [[libhgscvrp.download]]
    sha256 = "be05a2077e5006df93d9c042b59b99502b938432ce360bcde3db4eea10f12311"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libhgscvrp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8870ae94378639b575b1ed3e6cd3c503ab816b9b"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "36b646fa1fafea5f77a2624c461a767e7d1a46202602e4a390780341bad51952"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libhgscvrp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc846971ee8151b93fe6d2fe546a83a2245ce33f"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "bd751945e7d7997ba391938cb580bb4c804421e107fd568e3c1bcd7d999da62f"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e413fd5d0cfaa66c7a51b41d74c0973d2531180d"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "26f8973891a2c727a11f876d739c429be698e24ac86a11feeabc38d4e05ec2d2"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c5930b5b7682ecf82e8a666da3949f3bd5e05c0"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "ffe7954dec55a35114d55d8f4a54f9da8d7a960fa9b9cf131da711e135e8de52"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f37f9d7c4f0b84818220635d41977a133ef0e95"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "dfa4da4fb481b2ffa575f580bc100a23364468a2bb1bddebc1f136898fad27b4"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02db4b223b5e463eb8e15e869c31b3930894ed70"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "437505b09f4d6a2fa82cab5f2e9d9c1f4796347e745f051d49e6e17a3152e021"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fedbcd3fb499f003d6e7502feccc196c6882b24b"
os = "windows"

    [[libhgscvrp.download]]
    sha256 = "2728ef4a59dff8722e0aced5d506b36e9834a585d8b31edcb4f6f7513550fd81"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93e9478c2a2161c18f86547c2af6d29ca4329bc3"
os = "windows"

    [[libhgscvrp.download]]
    sha256 = "9222fd88781d060af87eb369950d675bed28a3bc9ca1ef8678ab6ae51991ac9d"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libhgscvrp]]
arch = "aarch64"
git-tree-sha1 = "80094a240a7b11ba2002db6520012dee269776a8"
os = "macos"

    [[libhgscvrp.download]]
    sha256 = "34e41c9a5d6b8b2b18a97fd6f2d5ce6c3e1eed2586982ed22c7a7bcac7a955d9"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-apple-darwin.tar.gz"
[[libhgscvrp]]
arch = "aarch64"
git-tree-sha1 = "06eae66478d6cf1ba70da7b6906f81b4efe3c979"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "6e7188fba93114492e96b7da3db56e37f9b95eb10c60c06b3e373309786084ec"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-linux-gnu.tar.gz"
[[libhgscvrp]]
arch = "aarch64"
git-tree-sha1 = "f720cb055b668e2f3b03dd89e6e5c2e3b1118110"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "8cabbceb3f01213c4f0a9057ec8f04b9de37de568a7bc6f01ae17a668dba6cbc"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.aarch64-linux-musl.tar.gz"
[[libhgscvrp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6192fe46b36bfe6a34ee67d6934d2bcf7f537a3c"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "3e2f2d7660aad05c8716e94ce2fb9f121d994cf2b9338c872af41cc232484c56"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[libhgscvrp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5c21dab6bd89f0b7f9592317ce7571f61d42f821"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "183f96c853373b81e136dcfea52c6daba939d13e467bfc72e3befa2d0ec4b2f1"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv6l-linux-musleabihf.tar.gz"
[[libhgscvrp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0ad3a6e587a090840475d59025e10696e937ad5"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "413cdf1110e7e2dc1cb3297044d2d265492d2d5afb4e2a8ecbaf0036872c40fb"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[libhgscvrp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c6402bf3b01b91bebc097cfb1540b2294d9c4e7c"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "d4dc466412463322bb0d1c4fd7431bd3365f353801fc9f8ea488067b3d26168f"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[libhgscvrp]]
arch = "i686"
git-tree-sha1 = "728e837b38b195c09047c5504fc2ce934bd44e4b"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "d20903d29fd0ef3a13eb6484bcd20fe26cb28b37f0e0226aa5f19d1f63050556"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-linux-gnu.tar.gz"
[[libhgscvrp]]
arch = "i686"
git-tree-sha1 = "c68af4c0abd36659a3aea228fde1f42b6b1dfaea"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "779fcdef92c281c6051b60cbd216c6cc4ed988522185004eb745c76ee3004057"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-linux-musl.tar.gz"
[[libhgscvrp]]
arch = "i686"
git-tree-sha1 = "da0b082dab1f02f5c36fc0d90e26e64ee5851f5d"
os = "windows"

    [[libhgscvrp.download]]
    sha256 = "6410d3c5a5962aefa50fab659a0fac550cb9e5cd40533d579d040cc7180fe397"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.i686-w64-mingw32.tar.gz"
[[libhgscvrp]]
arch = "powerpc64le"
git-tree-sha1 = "d41e4cbaacb48d35d27bb29aa9cf81d7f8133a10"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "0383592af83be6311bb3dbedcb588dfa58796bd929414551b248ad3f2ee069b3"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
git-tree-sha1 = "02bcd94ce25ef505cce3dc4f110a552f394f00db"
os = "macos"

    [[libhgscvrp.download]]
    sha256 = "3f6c8ce19d19443722b8f5c32a00cced080952473fffd15d08003b30d61e5cad"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-apple-darwin.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
git-tree-sha1 = "e413fd5d0cfaa66c7a51b41d74c0973d2531180d"
libc = "glibc"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "b9ba99c6c399da7c37d0ed1fdce5f35c4e76aa70490fc4ecc355c17c325ed9f4"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-linux-gnu.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
git-tree-sha1 = "1f37f9d7c4f0b84818220635d41977a133ef0e95"
libc = "musl"
os = "linux"

    [[libhgscvrp.download]]
    sha256 = "c5a8e2c68773f6d61ae84853748424324c8d5d55d7f01806ae2a7629e59c2a5f"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-linux-musl.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
git-tree-sha1 = "b8f803f473d6d4d79e3e892e820c74a98bf00d6c"
os = "freebsd"

    [[libhgscvrp.download]]
    sha256 = "fc05635d5115126feef9e1c671eaa5c65ca94c366d3f2edf1f78cb6323e5969c"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[libhgscvrp]]
arch = "x86_64"
git-tree-sha1 = "24530d0b8c84ae8f526cd25499b94f3f6b4c1031"
os = "windows"

    [[libhgscvrp.download]]
    sha256 = "c57c78ecb8c6785cb2e05ad13b1ace7537330e2789c77f5133b68f2df53d9f69"
    url = "https://github.com/chkwon/Libhgscvrp_jll.jl/releases/download/libhgscvrp-v0.0.1+0/libhgscvrp.v0.0.1.x86_64-w64-mingw32.tar.gz"
