# Autogenerated wrapper script for libhgscvrp_jll for x86_64-apple-darwin
export libhgscvrp

JLLWrappers.@generate_wrapper_header("libhgscvrp")
JLLWrappers.@declare_library_product(libhgscvrp, "@rpath/libhgscvrp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libhgscvrp,
        "lib/libhgscvrp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
